name: Deploy Upload Backend to AWS Lambda

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: npm

      - name: Install dependencies
        run: npm ci

      - name: Create deployment package
        run: zip -r function.zip . -x "node_modules/.cache/*" ".git/*"

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID_BMS_0 }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY_BMS_0 }}
          aws-region: ap-south-1

      - name: Deploy Lambda
        run: |
          aws lambda update-function-code \
            --function-name booking-management-system-node-be \
            --zip-file fileb://function.zip
